### ISSUE TITLE
Freeze linux

### ISSUE THREAD

**Issue by techpulse** [OgarProject/Ogar#99] opened 2015-07-12 14:24 UTC
It froze me for 15 seconds then put me back. Not sure if we can do anything regarding that

**Comment by techpulse** [comment] 2015-07-12 14:25
constantly happens now http://i.imgur.com/0F69NCN.png happen again, insane lag.. not server issue from what im aware lol

**Comment by anonprophet** [comment] 2015-07-12 14:29
how you add face ?

**Comment by techpulse** [comment] 2015-07-12 14:30
i use a ogar clone, it's nice :3

**Comment by joery1337** [comment] 2015-07-12 15:07
New commit brought the memory leak back, could that be a problem? It killed my entire server lol.

**Comment by techpulse** [comment] 2015-07-12 15:07
he said he fixed it though.. ugh xD

**Comment by joery1337** [comment] 2015-07-12 15:14
@techpulse 
I used an older sendPacket function and it works great for me.

`
// Custom prototype functions
WebSocket.prototype.sendPacket = function(packet) {
    // Send only if the buffer is empty
    if (this.readyState == WebSocket.OPEN && (this._socket.bufferSize == 0) && packet.build) {
        try {
            this.send(packet.build(), {binary: true});
        } catch (e) {
            console.log("[Error] "+e);
            // Remove socket
            this.emit('close');
            this.removeAllListeners();
        }
    } else if (!packet.build) {
        // Do nothing
        //console.log("[Warning] There was an error sending the packet!");
    } else {
        //console.log("[Warning] There was an error sending the packet to "+this.playerTracker.name);
        // Remove socket
        this.emit('close');
        this.removeAllListeners();
    }
};
`

**Comment by z3ntu** [comment] 2015-07-22 11:41
Please close this issue if the problem is solved!

**Closed** 2015-07-22 12:00 UTC
