### ISSUE TITLE
[Solved] Ogar Download

### ISSUE THREAD

**Issue by SamB440** [OgarProject/Ogar#654] opened 2016-07-31 17:43 UTC
Since the Ogar website is currently down, and not sure whether it will ever be up, could someone PLEASE send me the last exe file that was published? I have the old one but this does not work, it just shows a white screen. Thanks.

P.S will it ever be renewed?

**Comment by ItzLevvie** [comment] 2016-07-31 18:33
The old files will no longer work with the latest agario client because of the protocol changes

**Comment by SamB440** [comment] 2016-07-31 18:35
Which is why I'm asking for someone to send me the newest release, before the website went offline.

**Comment by ItzLevvie** [comment] 2016-07-31 18:48
"newest release" - @SamB440
 
There isn't any 'newest release', the last .exe build was built on June 2015 and Miniclip changed their protocol on May 2016, so this means that the .exe files will not work.

"P.S will it ever be renewed?"

I don't think so to be honest.

NOTE: You've to use the sources, binaries hasn't been updated for like 12 months now.

**Comment by SimonOrJ** [comment] 2016-08-01 21:39
If the problem is solved, please consider closing the issue. :)

**Comment by SamB440** [comment] 2016-08-02 10:03
It doesn't allow me to :/

**Comment by ItzLevvie** [comment] 2016-08-02 12:36
There should be a "Close issue" before the "Comment" button

**Closed** 2016-08-02 13:00 UTC
